import { z } from "zod";

// Same 10-digit rule as customer booking creation. A reference is a random
// 16-character hexadecimal token generated by lib/bookingReference.ts.
export const bookingAccessSchema = z.object({
  bookingReference: z
    .string()
    .trim()
    .regex(/^[a-fA-F0-9]{16}$/),
  phone: z
    .string()
    .trim()
    .max(32)
    .refine((phone) => phone.replace(/\D/g, "").length === 10),
});
